---
- name: Create reserved disk
  gcp_compute_disk:
    name: "{{ gcp_project }}-centosdisk"
    size_gb: 20
    source_image: 'projects/centos-cloud/global/images/family/centos-8'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: disk

- name: Create network resource for VM
  gcp_compute_network:
    name: "{{ gcp_project }}-network"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: network
  
- name: Create firewall rule for test VM
  gcp_compute_firewall:
    name: "{{ gcp_project }}-fw"
    network: "{{ network }}"
    allowed:
    - ip_protocol: tcp
      ports:
      - '22'
      - '80'
    source_ranges:
    - "{{ public_ip.ansible_facts.ipify_public_ip }}/32"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: Create temprary address for VM
  gcp_compute_address:
    name: "{{ gcp_project }}-externalip"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
    - https://www.googleapis.com/auth/compute
    state: present
  register: address

- name: Create the instance itself
  gcp_compute_instance:
    state: present
    name: "{{ gcp_project }}-vm"
    machine_type: e2-standard-2	
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
    network_interfaces:
      - network: "{{ network }}"
        access_configs:
          - name: 'External NAT'
            nat_ip: "{{ address }}"
            type: 'ONE_TO_ONE_NAT'
    metadata:
      ssh-keys: "{{ gcp_user_name}}:{{ lookup('file', '~/.ssh/emarsys-homework.pub') }} {{ gcp_user_name}}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
  register: instance

- name: Wait for SSH to come up
  wait_for: host={{ address.address }} port=22 delay=10 timeout=60
   
- name: wait for ssh authentication to come up (temporary, needs some digging, it is very inconsistent, although 1 minute works 100%)
  pause: 
    minutes: 1

- name: Add host to groupname
  add_host: 
    hostname: "{{ address.address }}"
    groupname: emarsys_homework_vm
...